# Site settings
title: Ariel's Blog
email: pontes.ariel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My first Jekyll blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arielpontes.github.io" # the base hostname & protocol for your site
twitter_username: arielpontes
github_username:  arielpontes

# Build settings
markdown: kramdown

exclude: [vendor]

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
